pipeline {
    agent any

    stages {
        stage('Springboot build') {
            steps {
                dir('match'){
                    sh '''
                    pwd
                    echo 'springboot build'
                    chmod +x gradlew
                    ./gradlew clean build
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully built SpringBoot "'
                }
                failure {
                    sh 'echo "Failed to build SpringBoot"'
                }
            }
        }

        stage('Dockerimage build') {
            steps {
                dir('match'){
                    sh '''
                    echo 'Dockerimage build'
                    docker build -t docker-springboot:0.0.1 .
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully built Docker image "'
                }
                failure {
                    sh 'echo "Failed to build Docker image "'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('match'){
                    sh '''
                    echo 'Deploy'

                    docker stop springboot
                    docker rm springboot

                    docker stop springboot_2
                    docker rm springboot_2

                    docker stop springboot_3
                    docker rm springboot_3


                    docker run -d -p 8080:8080 --name springboot docker-springboot:0.0.1
                    docker run -d -p 8081:8080 --name springboot_2 docker-springboot:0.0.1
                    docker run -d -p 8082:8080 --name springboot_3 docker-springboot:0.0.1
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully deployed "'
                }
                failure {
                    sh 'echo "Failed to deploy"'
                }
            }
        }
    }
}