pipeline {
    agent any

    tools{
        nodejs 'nodejs'
    }

    stages {
        stage('Install Dependencies') {
            steps {
                dir('trinityfront'){
                    sh '''
                    pwd
                    echo 'prepare'
                    npm install -g yarn

                    echo 'yarn install'
                    yarn install
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully "'
                }
                failure {
                    sh 'echo "Fail"'
                }
            }
        }

        stage('Build TypeScript') {
            steps {
                dir('trinityfront') {
                    script {
                        // TypeScript를 프로젝트 의존성으로 설치
                        sh 'yarn add --dev typescript'

                        // TypeScript 컴파일
                        sh 'npx tsc'
                    }
                }
            }
        }

        stage('Build') {
            steps {
                dir('trinityfront') {
                    sh '''
                    echo 'yarn build'
                    yarn build
                    '''
                }
            }
        }

        stage('Dockerimage build') {
            steps {
                dir('trinityfront'){
                    sh '''
                    echo 'Dockerimage build'
                    docker build -t docker-react:0.0.1 .
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully "'
                }
                failure {
                    sh 'echo "Fail"'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('trinityfront'){
                    sh '''
                    echo 'Deploy'                    

                    echo '컨테이너 삭제'
                    docker stop react
                    docker rm react

                    docker run -d -p 3000:3000 --name react docker-react:0.0.1
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully "'
                }
                failure {
                    sh 'echo "Fail"'
                }
            }
        }
    }
}