pipeline {
    agent any

    stages {
        stage('Springboot build') {
            steps {
                dir('trinity'){
                    sh '''
                    pwd
                    echo 'springboot build'
                    chmod +x gradlew
                    ./gradlew clean build
                    cp /var/jenkins_home/resources/application.yml springboot:/var/jenkins_home/workspace/Springboot/trinity/src/main/resources/application.yml
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully built SpringBoot "'
                }
                failure {
                    sh 'echo "Failed to build SpringBoot"'
                }
            }
        }

        stage('Docker image build') {
            steps {
                dir('trinity'){
                    sh '''
                    echo 'Docker image build'
                    docker build -t docker-springboot:0.0.1 .
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully built Docker image "'
                }
                failure {
                    sh 'echo "Failed to build Docker image "'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('trinity'){
                    sh '''
                    echo 'Deploy'

                    docker stop springboot
                    docker rm springboot

                    docker stop springboot_2
                    docker rm springboot_2

                    docker stop springboot_3
                    docker rm springboot_3

                    docker run -d -p 8080:8080 -v /var/jenkins_home/resources/application.yml:/var/jenkins_home/workspace/Springboot/trinity/src/main/resources/application.yml --name springboot docker-springboot:0.0.1
                    docker run -d -p 8081:8080 -v /var/jenkins_home/resources/application.yml:/var/jenkins_home/workspace/Springboot/trinity/src/main/resources/application.yml --name springboot_2 docker-springboot:0.0.1
                    docker run -d -p 8082:8080 -v /var/jenkins_home/resources/application.yml:/var/jenkins_home/workspace/Springboot/trinity/src/main/resources/application.yml --name springboot_3 docker-springboot:0.0.1

                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully deployed "'
                }
                failure {
                    sh 'echo "Failed to deploy"'
                }
            }
        }
    }
}